const PHOTO_FIELD_TYPE = {
  PERSONAL: 'PERSONAL',
  ATTACHMENT: 'ATTACHMENT',
};

const PHOTO_VALIDATION = {
  MAX_PHOTO_SIZE_IN_BYTES: 2 * 1024 * 1024,
  MAX_PHOTO_WIDTH: 500,
  MAX_PHOTO_HEIGHT: 500,
};

const PHOTO_SHAPE = {
  CIRCLE: { radius: 50 },
  SQUARE: { radius: 0 },
};

export { PHOTO_FIELD_TYPE, PHOTO_VALIDATION, PHOTO_SHAPE };
